In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
import pandas as pd

from sklearn.datasets import load_digits
digits = load_digits()

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,
                                                    test_size=0.2, random_state=42)

In [40]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\bhavy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9694444444444444

In [41]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9861111111111112

In [42]:
rf = RandomForestClassifier(n_estimators=500)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975

In [43]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [44]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [45]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [46]:
print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
print(get_score(SVC(), X_train, X_test, y_train, y_test))
print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

C:\Users\bhavy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9694444444444444
0.9861111111111112
0.9722222222222222


- `KFold` and `StratifiedKFold` are both cross-validation methods used to evaluate the performance of a machine learning model. 

- `KFold` splits the data into `k` equally sized folds and uses `k-1` folds for training and the remaining fold for testing. This process is repeated `k` times, with each fold used exactly once for testing. `KFold` does not take into account the distribution of the target variable and may result in imbalanced folds, especially if the target variable is not evenly distributed.

- `StratifiedKFold`, on the other hand, splits the data into `k` folds while preserving the percentage of samples for each class. This ensures that each fold has a similar distribution of the target variable, which is especially important for imbalanced datasets. `StratifiedKFold` is recommended for classification problems where the target variable is categorical.

- In summary, `KFold` is a general-purpose cross-validation method that can be used for any type of dataset, while `StratifiedKFold` is a specialized cross-validation method that is recommended for classification problems with imbalanced datasets.

In [47]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=10)
folds

StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

In [50]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=100), X_train, X_test, y_train, y_test))

C:\Users\bhavy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\bhavy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

In [51]:
print(scores_logistic, "\nMean: ", np.array(scores_logistic).mean())
print(scores_svm, "\nMean: ", np.array(scores_svm).mean())
print(scores_rf, "\nMean: ", np.array(scores_rf).mean())

[0.9055555555555556, 0.9611111111111111, 0.8777777777777778, 0.9277777777777778, 0.9444444444444444, 0.9666666666666667, 0.95, 0.9385474860335196, 0.8715083798882681, 0.9385474860335196] 
Mean:  0.928193668528864
[0.9444444444444444, 0.9888888888888889, 0.9277777777777778, 0.9666666666666667, 0.9833333333333333, 0.9888888888888889, 0.9888888888888889, 0.994413407821229, 0.9608938547486033, 0.9553072625698324] 
Mean:  0.9699503414028554
[0.9, 0.9722222222222222, 0.9333333333333333, 0.9166666666666666, 0.9611111111111111, 0.9722222222222222, 0.9722222222222222, 0.9608938547486033, 0.9162011173184358, 0.9329608938547486] 
Mean:  0.9437833643699565


In [52]:
from sklearn.model_selection import cross_val_score

In [58]:
cross_val_score(LogisticRegression(), digits.data, digits.target)
cross_val_score(SVC(), digits.data, digits.target)
cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)

C:\Users\bhavy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\bhavy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stab

array([0.91944444, 0.91944444, 0.95821727, 0.96100279, 0.92200557])